# Generated by Django 6.1 on 2026-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_description',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
