# Generated by Django 6.1 on 2026-08-17 14:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0003_orderitem_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_code',
            field=models.UUIDField(editable=False),
        ),
    ]
