# Generated by Django 6.1 on 2026-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PS', 'payment slip'), ('CC', 'credit card')], default='PS', max_length=2),
        ),
    ]
