# Generated by Django 6.1 on 2026-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
