# Generated by Django 6.1 on 2026-08-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_doc',
            field=models.CharField(default='null', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
